#!/usr/bin/env bash
# Does the following:
#   Create file /var/run/myscript.pid containing script PID.
#   Displays "To infinity and beyond" indefinitely
#   Displays "I hate the kill command" upon receiving SIGTERM
#   Displays "Y U no love me?!" upon receiving SIGINT
#   Delete file /var/run/myscript.pid and terminate upon
#+  receiving SIGQUIT or SIGTERM.

terminator() {
  rm /var/run/myscript.pid
  exit
}

echo "$$" > /var/run/myscript.pid

while true
do
  echo "To infinity and beyond"
  sleep 2
  trap 'echo "Y U no love me?!"' SIGINT
  trap 'echo "I hate the kill command" && terminator' SIGTERM
  trap 'terminator' SIGQUIT
done
