#!/usr/bin/env bash
# Display contents of file `/etc/passwd`.
#   Only display username, user id, and user home directory path.

while read -r passwd; do
  echo "$passwd" | cut -d ':' -f1,3,6
done < "/etc/passwd"
