#!/usr/bin/env bash
# Display "Best School" 10 times using while loop.
#   On the 9th iteration, display "Hi" before "Best School".

cont=0

while [ $cont -lt 10 ]
do
  if [ $cont -eq 9 ]
  then
    echo "Hi"
  fi
  echo "Best School"
  (( cont++ ))
done
