#!/usr/bin/env bash
# Loops from 1 to 10 and displays:
#   "bad luck" for 4th iteration
#   "good luck" for 8th iteration
#   "Best School" for all other iterations

cont=0

while [ $cont -lt 10 ]
do
  if [ $cont -eq 3 ]
  then
    echo "bad luck"
  elif [ $cont -eq 7 ]
  then
    echo "good luck"
  else
    echo "Best School"
  fi
  (( cont++ ))
done
